### PR TITLE
Added password-generator to js-projects

### PR DESCRIPTION
**Pull request by ibrahimraimi**
Here is the password generator project

### CODE REVIEW

**Comment by namangupta1399** [comment]
Useful app @IbrahimOlayinka .

**Review by namangupta1399 — APPROVED** [review]

**Comment by chryzcode** [comment]
@namangupta1399 @jomefavourite please check this project out.  

The functionality .....

**Review by jomefavourite — APPROVED** [review]
Everything looks good, thanks for contributing @IbrahimOlayinka

**Comment by ibrahimraimi** [comment]
@namangupta1399 thank you

**Pull request merged**
