### PR TITLE
Filter functionality project

### PR DESCRIPTION
**Pull request by jomefavourite**
A Custom Search Filter functionality built using JavaScript

### CODE REVIEW

**Comment by jomefavourite** [comment]
@namangupta1399 Here's another project

**Comment by namangupta1399** [comment]
Good one @jomefavourite . 
You can prevent the page refresh if the user hits `Enter` key
I will also try to add some of my own projects like these.

**Comment by namangupta1399** [comment]
@chryzcodez , pls merge the PR.

**Comment by jomefavourite** [comment]
Thanks, @namangupta1399, I didn't test for the Enter key, I'll correct that.

**Comment by chryzcode** [comment]
Please do that @jomefavourite 😉

**Pull request merged**
